version: '2'

services:

  app:
    image: arecker/santabot:latest
    build: .

  db:
    image: postgres
    secrets:
      - db-name
      - db-user
      - db-password
    environment:
      POSTGRES_DB_FILE: /var/run/secrets/db-name
      POSTGRES_USER_FILE: /var/run/secrets/db-user
      POSTGRES_PASSWORD_FILE: /run/secrets/db-password
    volumes:
      - santabot_db:/var/lib/postgresql/data

secrets:
  db-name:
    external: true
  db-user:
    external: true
  db-password:
    external: true

volumes:
  santabot_db: {}