# Generated by Django 2.0 on 2017-12-22 04:09

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Participant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address_1', models.CharField(max_length=280)),
                ('address_2', models.CharField(blank=True, max_length=280, null=True)),
                ('city', models.CharField(max_length=280)),
                ('state', models.CharField(blank=True, max_length=2, null=True)),
                ('province', models.CharField(blank=True, max_length=280, null=True)),
                ('country', models.CharField(blank=True, max_length=280, null=True)),
                ('zip_code', models.CharField(blank=True, max_length=280, null=True)),
                ('notes', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
