# Generated by Django 2.0 on 2017-12-22 04:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='address_1',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
        migrations.AlterField(
            model_name='participant',
            name='city',
            field=models.CharField(blank=True, max_length=280, null=True),
        ),
    ]
