# Generated by Django 2.0 on 2017-12-22 04:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0002_auto_20171222_0410'),
    ]

    operations = [
        migrations.AddField(
            model_name='participant',
            name='default_exclusions',
            field=models.ManyToManyField(to='matching.Participant'),
        ),
    ]
