# Generated by Django 2.0 on 2017-12-22 04:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('matching', '0003_participant_default_exclusions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='participant',
            name='default_exclusions',
            field=models.ManyToManyField(blank=True, null=True, to='matching.Participant'),
        ),
    ]
